### ISSUE TITLE
Duplicate User Validation

### ISSUE THREAD

**Issue by DavidmKlunk** [UCCS-CS4300-5300/Group2-fall2024#31]

**Comment by hAnguyen1517** [comment]
I will check and keep everyone updated!

**Comment by DavidmKlunk** [comment]
Ensure that users must provide unique email addresses upon account creation

Current codebase suggests they are being filtered, but ensure.

**Comment by hAnguyen1517** [comment]
Test case 1: Validate email; each user has to use a unique email to create an account. (Passed the test) 
![image](https://github.com/user-attachments/assets/e6da1c44-c6ab-47d9-97dc-f6d279f941e7)
Message I see: 
![image](https://github.com/user-attachments/assets/8ddb13dc-a7fa-4360-b237-154aba39c7ae)

#######################################

Test Case 2: Validate username; it has to be unique ---> Passed the test
![image](https://github.com/user-attachments/assets/bd81ebeb-745b-4c60-b627-136e702dbf5b)
Message I see:
![image](https://github.com/user-attachments/assets/86134e0d-219c-4a88-98a1-333de2b1faa8)

**Comment by hAnguyen1517** [comment]
Duplicate User Validation has been tested, and the results are as expected!

**Comment by DavidmKlunk** [comment]
Worked as expected, issue closed
